### ISSUE TITLE
Features stories API endpoint

### ISSUE THREAD

**Issue by ilyakatz** [ilyakatz/growth_tracker#1]
Currently 

`http://localhost:3000/stories.json` 

returns an empty hash. 

Complete it to return an array of featured stories. This will require

Models:
- [x] Story model (with title, text, etc)
- [x] Tag model (for the hastags)
- [x] Association of the story model to tag model (using `has_many` http://guides.rubyonrails.org/association_basics.html#the-has-many-association)
- [x] Scope in the `Story` model to return featured stories http://guides.rubyonrails.org/active_record_querying.html#scopes

Data
- [x] Populate a few stories in database (perhaps use seed.rb to create a few dummy stories) http://www.xyzpub.com/en/ruby-on-rails/3.2/seed_rb.html

Controller
- [x] Update stories_controller to return json representation http://edgeapi.rubyonrails.org/classes/ActionController/Responder.html
- [x] Update test  `rspec spec/controllers/stories_controller_spec.rb` to test that a json representation of stories is returned (http://betterspecs.org/)

**Comment by ilyakatz** [comment]
https://github.com/rails/jbuilder for the index.json.jbuilder view

**Comment by madamkiwi** [comment]
i can't get the rspec to work :(  The response (console output) has a bunch of stuff but does not have the story title/text, and response.body is empty.

require 'rails_helper'

RSpec.describe StoriesController, :type => :controller do
  it "returns featured stories" do
    get :index, format: :json
    expect(response).to be_success
    #response should contain json with list of featured stories"
    body = JSON.parse(response.body)
    expect(body).to eq 1
    title = body['title']
    text = body['text']
  end
end

**Comment by madamkiwi** [comment]
where should I add data?  And do you use factory_girl?  I added this in spec/models/story_spec.rb but still doesn't show.
require 'rails_helper'

RSpec.describe Story, :type => :model do
  it 'creates a new story' do
    story = Story.new(:title => "Bootie", :text => "I almost got into a fight with a guy who requested me to pay for his spilled drink.")
    expect(story.title).to eq "Bootie"
  end
end

**Comment by ilyakatz** [comment]
add it right in your test. For a controller test, make sure to use `create` since `new` only creates it in memory and doesn't persist to database

so taking your example above

``` ruby
RSpec.describe StoriesController, :type => :controller do
  it "returns featured stories" do
    # create a new story in DB
    story = Story.create(
      title: "Bootie",
      text: "I almost got into a fight with a guy who requested me to pay for his spilled drink."
    )

    get :index, format: :json
    expect(response).to be_success
  end
end
```

**Comment by ilyakatz** [comment]
re: factory_girl

Yes, I usually use it. It's not really necessary yet, but if you want to get more practice, get the tests to pass and then rewrite it using factory_girl

**Comment by madamkiwi** [comment]
aha!

**Comment by madamkiwi** [comment]
![img_1530](https://cloud.githubusercontent.com/assets/4252002/13337673/a6d802f8-dbd1-11e5-9867-10386d923016.JPG)
